use vk;
insert into communities (id, name, description, admin_id) values (1, 'Bradtke-Schumm', 'justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus', 60);
insert into communities (id, name, description, admin_id) values (2, 'Rodriguez LLC', 'dolor quis odio consequat varius integer ac leo pellentesque ultrices', 33);
insert into communities (id, name, description, admin_id) values (3, 'Koch and Sons', 'scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas', 92);
insert into communities (id, name, description, admin_id) values (4, 'Hilll, Davis and Schmitt', 'sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel', 15);
insert into communities (id, name, description, admin_id) values (5, 'O''Kon-Keeling', 'ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio', 38);
insert into communities (id, name, description, admin_id) values (6, 'Pouros Group', 'porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea', 83);
insert into communities (id, name, description, admin_id) values (7, 'Schiller and Sons', 'duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis', 59);
insert into communities (id, name, description, admin_id) values (8, 'Carter-Rempel', 'non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam', 29);
insert into communities (id, name, description, admin_id) values (9, 'Shanahan, Moen and Schroeder', 'sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere', 21);
insert into communities (id, name, description, admin_id) values (10, 'Frami and Sons', 'massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt', 96);
insert into communities (id, name, description, admin_id) values (11, 'Borer, Nicolas and Zboncak', 'quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus', 19);
insert into communities (id, name, description, admin_id) values (12, 'Schmidt, Thompson and Lebsack', 'nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit', 49);
insert into communities (id, name, description, admin_id) values (13, 'Zulauf Inc', 'erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in', 36);
insert into communities (id, name, description, admin_id) values (14, 'Mosciski and Sons', 'cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis', 88);
insert into communities (id, name, description, admin_id) values (15, 'Rempel, Feeney and Tillman', 'ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate', 1);
insert into communities (id, name, description, admin_id) values (16, 'Johns-Anderson', 'aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam', 9);
insert into communities (id, name, description, admin_id) values (17, 'Hahn, Halvorson and Klocko', 'mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a', 59);
insert into communities (id, name, description, admin_id) values (18, 'Gleichner, Hettinger and Crist', 'magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean', 80);
insert into communities (id, name, description, admin_id) values (19, 'Hauck Group', 'at nunc commodo placerat praesent blandit nam nulla integer pede justo', 76);
insert into communities (id, name, description, admin_id) values (20, 'Breitenberg, Abshire and Brown', 'congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus', 61);
insert into communities (id, name, description, admin_id) values (21, 'Christiansen, Corkery and Ortiz', 'penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque', 62);
insert into communities (id, name, description, admin_id) values (22, 'Hermiston, Leuschke and Christiansen', 'tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci', 36);
insert into communities (id, name, description, admin_id) values (23, 'Schmeler-Tillman', 'potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis', 54);
insert into communities (id, name, description, admin_id) values (24, 'Koss Inc', 'ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien', 54);
insert into communities (id, name, description, admin_id) values (25, 'Greenholt, Wehner and Parisian', 'mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes', 25);
insert into communities (id, name, description, admin_id) values (26, 'Dietrich-Macejkovic', 'lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit', 29);
insert into communities (id, name, description, admin_id) values (27, 'Wolff LLC', 'primis in faucibus orci luctus et ultrices posuere cubilia curae', 11);
insert into communities (id, name, description, admin_id) values (28, 'Larson-Kohler', 'et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo', 49);
insert into communities (id, name, description, admin_id) values (29, 'Lesch, Cruickshank and Pfannerstill', 'massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 74);
insert into communities (id, name, description, admin_id) values (30, 'Wiegand, Bergstrom and Gusikowski', 'massa id lobortis convallis tortor risus dapibus augue vel accumsan', 97);
insert into communities (id, name, description, admin_id) values (31, 'Schaden-Ruecker', 'pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis', 65);
insert into communities (id, name, description, admin_id) values (32, 'Lind Inc', 'odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius', 99);
insert into communities (id, name, description, admin_id) values (33, 'McKenzie, Weber and Lehner', 'nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat', 44);
insert into communities (id, name, description, admin_id) values (34, 'Kessler, Maggio and Heidenreich', 'ut at dolor quis odio consequat varius integer ac leo', 81);
insert into communities (id, name, description, admin_id) values (35, 'Dickens-Treutel', 'ante ipsum primis in faucibus orci luctus et ultrices posuere', 91);
insert into communities (id, name, description, admin_id) values (36, 'Lowe, Fahey and Witting', 'eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit', 85);
insert into communities (id, name, description, admin_id) values (37, 'Miller, Schimmel and Witting', 'gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem', 73);
insert into communities (id, name, description, admin_id) values (38, 'Ullrich-Wunsch', 'sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu', 26);
insert into communities (id, name, description, admin_id) values (39, 'Zboncak Group', 'faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae', 76);
insert into communities (id, name, description, admin_id) values (40, 'Renner-Schultz', 'eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus', 44);
insert into communities (id, name, description, admin_id) values (41, 'Oberbrunner, Kutch and Boyer', 'lorem ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius', 79);
insert into communities (id, name, description, admin_id) values (42, 'Konopelski Group', 'fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam', 100);
insert into communities (id, name, description, admin_id) values (43, 'Goldner, Schoen and Sauer', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', 29);
insert into communities (id, name, description, admin_id) values (44, 'Kub, Morissette and Mohr', 'sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet', 9);
insert into communities (id, name, description, admin_id) values (45, 'Walker-Hahn', 'congue risus semper porta volutpat quam pede lobortis ligula sit amet', 91);
insert into communities (id, name, description, admin_id) values (46, 'Prohaska and Sons', 'morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo', 77);
insert into communities (id, name, description, admin_id) values (47, 'Okuneva, Hintz and Sauer', 'consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl', 67);
insert into communities (id, name, description, admin_id) values (48, 'Langworth-Gislason', 'duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque', 97);
insert into communities (id, name, description, admin_id) values (49, 'Farrell Group', 'congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci', 67);
insert into communities (id, name, description, admin_id) values (50, 'Herman Inc', 'feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet', 44);
insert into communities (id, name, description, admin_id) values (51, 'Hartmann-Hand', 'donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est', 33);
insert into communities (id, name, description, admin_id) values (52, 'Hammes LLC', 'nunc viverra dapibus nulla suscipit ligula in lacus curabitur at', 75);
insert into communities (id, name, description, admin_id) values (53, 'Thompson, Bogan and Hoppe', 'iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque', 4);
insert into communities (id, name, description, admin_id) values (54, 'Thompson LLC', 'lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis', 78);
insert into communities (id, name, description, admin_id) values (55, 'Bartoletti Inc', 'vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy', 91);
insert into communities (id, name, description, admin_id) values (56, 'Pfannerstill-Grady', 'nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo', 43);
insert into communities (id, name, description, admin_id) values (57, 'Davis-Willms', 'congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie', 48);
insert into communities (id, name, description, admin_id) values (58, 'Hackett LLC', 'a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus', 27);
insert into communities (id, name, description, admin_id) values (59, 'Kuhn, Krajcik and Schimmel', 'ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices', 34);
insert into communities (id, name, description, admin_id) values (60, 'Wiegand Group', 'dui maecenas tristique est et tempus semper est quam pharetra magna', 33);
insert into communities (id, name, description, admin_id) values (61, 'Schinner Inc', 'et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis', 76);
insert into communities (id, name, description, admin_id) values (62, 'Schumm-Konopelski', 'justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam', 57);
insert into communities (id, name, description, admin_id) values (63, 'Schuster Group', 'proin leo odio porttitor id consequat in consequat ut nulla sed', 35);
insert into communities (id, name, description, admin_id) values (64, 'Kassulke, Langworth and Stiedemann', 'eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia', 57);
insert into communities (id, name, description, admin_id) values (65, 'Connelly-Champlin', 'magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi', 13);
insert into communities (id, name, description, admin_id) values (66, 'Berge-Swaniawski', 'in purus eu magna vulputate luctus cum sociis natoque penatibus et', 6);
insert into communities (id, name, description, admin_id) values (67, 'Mante Group', 'auctor gravida sem praesent id massa id nisl venenatis lacinia', 92);
insert into communities (id, name, description, admin_id) values (68, 'Ondricka-Grady', 'sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue', 73);
insert into communities (id, name, description, admin_id) values (69, 'Runolfsson and Sons', 'quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt', 64);
insert into communities (id, name, description, admin_id) values (70, 'Carroll, Schaden and Balistreri', 'nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus', 30);
insert into communities (id, name, description, admin_id) values (71, 'Senger LLC', 'suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non', 35);
insert into communities (id, name, description, admin_id) values (72, 'Macejkovic-Waters', 'dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat', 21);
insert into communities (id, name, description, admin_id) values (73, 'Block, Robel and Bernhard', 'scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis', 3);
insert into communities (id, name, description, admin_id) values (74, 'Luettgen Inc', 'nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel', 45);
insert into communities (id, name, description, admin_id) values (75, 'Kerluke LLC', 'neque aenean auctor gravida sem praesent id massa id nisl', 17);
insert into communities (id, name, description, admin_id) values (76, 'Langworth LLC', 'in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum', 54);
insert into communities (id, name, description, admin_id) values (77, 'Herman, Dickens and Doyle', 'porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis', 9);
insert into communities (id, name, description, admin_id) values (78, 'Crona-Stark', 'nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem', 35);
insert into communities (id, name, description, admin_id) values (79, 'Weber, Will and Steuber', 'morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis', 75);
insert into communities (id, name, description, admin_id) values (80, 'Howe Group', 'luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio', 24);
insert into communities (id, name, description, admin_id) values (81, 'Huels Group', 'risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet', 70);
insert into communities (id, name, description, admin_id) values (82, 'McCullough and Sons', 'mattis odio donec vitae nisi nam ultrices libero non mattis', 75);
insert into communities (id, name, description, admin_id) values (83, 'Schiller Inc', 'vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis', 68);
insert into communities (id, name, description, admin_id) values (84, 'Marks-Nienow', 'arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc', 40);
insert into communities (id, name, description, admin_id) values (85, 'Hirthe, Huel and Runolfsson', 'dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non', 1);
insert into communities (id, name, description, admin_id) values (86, 'Sipes-Stroman', 'sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis', 12);
insert into communities (id, name, description, admin_id) values (87, 'Nikolaus LLC', 'ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem', 15);
insert into communities (id, name, description, admin_id) values (88, 'Greenfelder-Ferry', 'quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id', 91);
insert into communities (id, name, description, admin_id) values (89, 'Witting-Bradtke', 'mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus', 87);
insert into communities (id, name, description, admin_id) values (90, 'Ritchie-Dibbert', 'massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo', 49);
insert into communities (id, name, description, admin_id) values (91, 'Reichert and Sons', 'dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut', 17);
insert into communities (id, name, description, admin_id) values (92, 'Batz, Green and Deckow', 'vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus', 7);
insert into communities (id, name, description, admin_id) values (93, 'Rice-Bode', 'nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus', 39);
insert into communities (id, name, description, admin_id) values (94, 'Nikolaus Inc', 'eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero', 20);
insert into communities (id, name, description, admin_id) values (95, 'Huel-Abbott', 'libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum', 4);
insert into communities (id, name, description, admin_id) values (96, 'Konopelski-Hane', 'mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus', 14);
insert into communities (id, name, description, admin_id) values (97, 'Douglas-Lehner', 'velit id pretium iaculis diam erat fermentum justo nec condimentum', 26);
insert into communities (id, name, description, admin_id) values (98, 'Langworth and Sons', 'at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit', 75);
insert into communities (id, name, description, admin_id) values (99, 'Torphy LLC', 'venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus', 45);
insert into communities (id, name, description, admin_id) values (100, 'Heidenreich, Yost and Sipes', 'sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui', 49);
