use vk;
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (1, 'M', '2005-01-26', 56, 'heuristic', 'Santiago', 'Philippines');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (2, 'M', '2006-10-08', 55, 'Reduced', 'Krasnyy Kholm', 'Russia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (3, 'F', '2004-12-29', 87, 'asymmetric', 'Pampachiri', 'Peru');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (4, 'M', '2007-08-19', 93, 'context-sensitive', 'Zhenqian', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (5, 'F', '1996-11-07', 50, 'Digitized', 'Cipinang', 'Indonesia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (6, 'F', '2005-04-19', 74, '24/7', 'Faro', 'Portugal');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (7, 'M', '1996-05-01', 2, 'methodical', 'Kansas City', 'United States');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (8, 'F', '1994-10-11', 59, 'Polarised', 'Néa Éfesos', 'Greece');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (9, 'M', '2010-05-25', 58, 'process improvement', 'Pecna', 'Poland');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (10, 'M', '2004-01-02', 67, 'Front-line', 'At-Bashi', 'Kyrgyzstan');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (11, 'M', '1994-02-20', 6, 'encryption', 'Namboongan', 'Philippines');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (12, 'M', '1992-01-16', 25, 'open system', 'Qadsīyā', 'Syria');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (13, 'F', '2008-01-19', 66, 'explicit', 'Sviblovo', 'Russia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (14, 'M', '1994-10-22', 31, 'Horizontal', 'Uścimów Stary', 'Poland');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (15, 'F', '1992-01-29', 34, 'transitional', 'Kongjiafang', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (16, 'M', '1992-05-19', 26, 'Upgradable', 'Yashan', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (17, 'F', '1991-12-18', 33, 'Vision-oriented', 'Sutysky', 'Ukraine');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (18, 'M', '1992-12-10', 35, 'Profound', 'Moya', 'Comoros');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (19, 'F', '1995-06-09', 81, 'radical', 'Shkodër', 'Albania');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (20, 'M', '1993-03-28', 74, 'Polarised', 'Cuiabá', 'Brazil');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (21, 'M', '1990-08-29', 91, 'optimal', 'Wujiashan', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (22, 'M', '1993-01-16', 80, 'matrix', 'Itumbiara', 'Brazil');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (23, 'F', '2008-06-02', 71, 'process improvement', 'Hearst', 'Canada');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (24, 'F', '1998-01-19', 92, '5th generation', 'Xiaoyan', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (25, 'M', '2005-08-06', 65, 'Decentralized', 'Lixu', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (26, 'M', '2009-06-10', 24, 'local', 'Beijie', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (27, 'M', '1995-10-06', 51, 'Object-based', 'Yangiqo‘rg‘on', 'Uzbekistan');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (28, 'M', '2007-12-17', 20, 'neutral', 'Paris 08', 'France');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (29, 'M', '1992-12-21', 51, 'asynchronous', 'El Puente', 'Honduras');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (30, 'M', '1993-01-09', 93, 'stable', 'Bamban', 'Philippines');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (31, 'F', '1996-05-23', 89, 'forecast', 'Orerokpe', 'Nigeria');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (32, 'M', '2007-11-30', 62, 'Digitized', 'Sumoto', 'Japan');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (33, 'F', '2009-03-25', 44, 'Persevering', 'Cartagena', 'Colombia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (34, 'F', '1997-04-18', 69, 'optimal', 'Chernyshkovskiy', 'Russia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (35, 'M', '2003-10-02', 61, 'Proactive', 'Dalang', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (36, 'F', '1995-07-24', 29, 'Realigned', 'Gul’cha', 'Kyrgyzstan');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (37, 'M', '1998-10-26', 65, '4th generation', 'Ierápetra', 'Greece');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (38, 'F', '2007-05-19', 13, 'archive', 'Gonça', 'Portugal');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (39, 'F', '2009-11-21', 75, 'Graphical User Interface', 'Przeworsk', 'Poland');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (40, 'M', '1991-02-14', 62, 'Right-sized', 'Andoany', 'Madagascar');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (41, 'M', '2009-04-01', 5, 'throughput', 'Encañada', 'Peru');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (42, 'M', '1994-03-08', 67, 'Proactive', 'Kungsör', 'Sweden');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (43, 'M', '2003-07-17', 79, 'Self-enabling', 'Ángeles', 'Costa Rica');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (44, 'M', '2005-10-22', 50, 'User-friendly', 'Toulouse', 'France');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (45, 'M', '2009-03-31', 12, 'contextually-based', 'Huanglong', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (46, 'M', '2002-04-03', 38, 'responsive', 'Qingfa', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (47, 'M', '1993-07-18', 18, 'attitude', 'Águas de Lindóia', 'Brazil');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (48, 'M', '1990-11-27', 75, 'incremental', 'Santai', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (49, 'M', '2002-11-06', 75, 'time-frame', 'Goodlands', 'Mauritius');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (50, 'M', '1995-09-24', 29, 'superstructure', 'Novobiryusinskiy', 'Russia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (51, 'M', '1991-08-10', 25, 'Profit-focused', 'Adiwerna', 'Indonesia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (52, 'M', '1998-11-26', 78, 'website', 'Kunčina', 'Czech Republic');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (53, 'M', '1997-08-24', 18, 'intermediate', 'Courbevoie', 'France');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (54, 'M', '1997-01-29', 78, 'dynamic', 'Xinji', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (55, 'M', '1991-12-20', 4, 'zero tolerance', 'Bagamoyo', 'Tanzania');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (56, 'F', '1993-08-26', 65, 'Mandatory', 'Kladno', 'Czech Republic');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (57, 'F', '1990-08-22', 77, 'asymmetric', 'Shuitianzhuang', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (58, 'M', '1996-09-11', 10, 'user-facing', 'Kotakan Selatan', 'Indonesia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (59, 'F', '2000-12-08', 23, 'responsive', 'Nogueira do Cravo', 'Portugal');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (60, 'F', '2001-04-02', 20, 'firmware', 'Rocky Mountain House', 'Canada');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (61, 'F', '2007-09-22', 80, 'eco-centric', 'Tianya', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (62, 'F', '2003-12-19', 80, 'Ameliorated', 'Itaitinga', 'Brazil');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (63, 'F', '2007-03-13', 77, 'User-friendly', 'Wenshang', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (64, 'F', '2003-06-14', 97, 'implementation', 'Esquina', 'Argentina');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (65, 'F', '2001-09-16', 93, 'discrete', 'Aţ Ţafīlah', 'Jordan');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (66, 'F', '2005-11-30', 100, 'array', 'Västerås', 'Sweden');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (67, 'M', '2004-06-09', 35, 'concept', 'Corredoura', 'Portugal');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (68, 'M', '2010-07-06', 90, 'Face to face', 'Yallahs', 'Jamaica');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (69, 'F', '1991-03-15', 75, 'non-volatile', 'Vänersborg', 'Sweden');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (70, 'M', '1996-01-13', 72, 'zero administration', 'Pingding', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (71, 'M', '1999-10-20', 89, 'Operative', 'Yurla', 'Russia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (72, 'M', '2001-09-13', 9, 'core', 'Halmstad', 'Sweden');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (73, 'F', '1996-05-11', 5, 'Cloned', 'Xin’an', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (74, 'M', '2009-10-25', 15, 'Graphic Interface', 'Vincennes', 'France');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (75, 'F', '1993-07-19', 86, 'Cross-platform', 'La Tigra', 'Argentina');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (76, 'F', '2010-04-12', 12, 'Multi-lateral', 'Ozamiz City', 'Philippines');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (77, 'M', '1993-11-12', 25, 'Business-focused', 'Gebre Guracha', 'Ethiopia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (78, 'M', '1991-02-17', 82, 'systematic', 'Jaša Tomić', 'Serbia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (79, 'F', '1995-05-08', 43, 'migration', 'Ouégoa', 'New Caledonia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (80, 'F', '1998-04-27', 19, 'Ameliorated', 'Barishāl', 'Pakistan');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (81, 'F', '2001-10-30', 96, 'eco-centric', 'Kumai', 'Indonesia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (82, 'M', '1999-08-21', 8, 'Graphical User Interface', 'Quinjalca', 'Peru');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (83, 'M', '1991-09-28', 37, 'Ergonomic', 'Debrecen', 'Hungary');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (84, 'M', '2008-08-12', 89, 'real-time', 'Port-Gentil', 'Gabon');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (85, 'F', '1996-02-15', 88, 'intranet', 'Sinamaica', 'Venezuela');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (86, 'M', '1999-09-20', 89, 'groupware', 'San Agustin', 'Mexico');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (87, 'M', '1996-02-22', 38, 'holistic', 'Fort Worth', 'United States');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (88, 'F', '2005-11-10', 53, 'Fundamental', 'Ishii', 'Japan');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (89, 'M', '2002-10-28', 37, 'Stand-alone', 'Wintzenheim', 'France');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (90, 'F', '2004-11-11', 5, 'website', 'Smimou', 'Morocco');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (91, 'M', '2000-12-06', 77, 'Monitored', 'Tabalong', 'Philippines');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (92, 'F', '2001-03-27', 85, 'knowledge user', 'Karanganyar', 'Indonesia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (93, 'M', '2003-10-25', 14, 'Balanced', 'Nanmu', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (94, 'F', '2006-08-13', 49, 'Virtual', 'Ribeira do Pombal', 'Brazil');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (95, 'M', '1991-09-30', 96, 'concept', 'Guanli', 'China');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (96, 'M', '2000-06-16', 59, 'Balanced', 'Saynshand', 'Mongolia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (97, 'F', '1994-02-04', 10, 'strategy', 'Huddinge', 'Sweden');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (98, 'F', '1992-07-26', 90, 'success', 'Pasanggrahan', 'Indonesia');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (99, 'M', '1996-05-28', 97, 'Vision-oriented', 'Mūsa Khel Bāzār', 'Pakistan');
insert into profiles (user_id, gender, birthday, photo_id, user_status, city, country) values (100, 'M', '2009-08-08', 53, 'discrete', 'Dushanbe', 'Tajikistan');
