insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (1, 'f', '2020-11-25', 1, 'Monthly', 'Lucan', 'Ireland');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (2, 'f', '2020-10-30', 2, 'Seldom', 'Kofelē', 'Ethiopia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (3, 'm', '2021-01-27', 3, 'Once', 'Schroeder', 'Brazil');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (4, 'm', '2020-11-13', 4, 'Once', 'Beni Khiar', 'Tunisia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (5, 'f', '2020-12-07', 5, 'Monthly', 'Santa Rosa', 'Mexico');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (6, 'm', '2021-02-02', 6, 'Once', 'Samanco', 'Peru');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (7, 'm', '2021-02-23', 7, 'Seldom', 'Ágios Vasíleios', 'Greece');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (8, 'm', '2020-10-11', 8, 'Seldom', 'Moluo', 'China');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (9, 'f', '2020-11-14', 9, 'Daily', 'Kalāt', 'Pakistan');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (10, 'm', '2020-10-03', 10, 'Monthly', 'Bambang', 'Philippines');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (11, 'f', '2020-07-22', 11, 'Weekly', 'Elele', 'Nigeria');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (12, 'f', '2020-10-11', 12, 'Often', 'Magaozhuang', 'China');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (13, 'f', '2020-10-30', 13, 'Yearly', 'Hatu Buh', 'China');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (14, 'm', '2021-05-29', 14, 'Once', 'Kabba', 'Nigeria');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (15, 'm', '2021-02-01', 15, 'Never', 'Wielka Nieszawka', 'Poland');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (16, 'm', '2021-02-04', 16, 'Weekly', 'Ozimek', 'Poland');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (17, 'f', '2021-05-27', 17, 'Monthly', 'Swedru', 'Ghana');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (18, 'f', '2020-12-13', 18, 'Weekly', 'Gali', 'Georgia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (19, 'f', '2021-05-02', 19, 'Monthly', 'Sukaraja', 'Indonesia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (20, 'f', '2020-11-07', 20, 'Monthly', 'Olupona', 'Nigeria');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (21, 'm', '2021-06-15', 21, 'Daily', 'Guihing Proper', 'Philippines');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (22, 'f', '2020-08-23', 22, 'Seldom', 'Tembayangan Barat', 'Indonesia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (23, 'm', '2020-12-15', 23, 'Never', 'Yiyang', 'China');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (24, 'f', '2020-08-15', 24, 'Weekly', 'Svay Rieng', 'Cambodia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (25, 'm', '2021-02-09', 25, 'Yearly', 'Sukacai', 'Indonesia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (26, 'm', '2020-08-03', 26, 'Once', 'Hopetown', 'South Africa');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (27, 'f', '2021-05-17', 27, 'Often', 'Gwangjeok', 'South Korea');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (28, 'm', '2020-07-28', 28, 'Seldom', 'Segezha', 'Russia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (29, 'f', '2020-07-23', 29, 'Monthly', 'Laleng', 'Indonesia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (30, 'f', '2021-03-26', 30, 'Yearly', 'Xucheng', 'China');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (31, 'f', '2020-10-28', 31, 'Once', 'Yushan', 'China');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (32, 'm', '2021-06-27', 32, 'Weekly', 'Manhan', 'Mongolia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (33, 'f', '2021-06-21', 33, 'Yearly', 'Miandrarivo', 'Madagascar');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (34, 'f', '2020-11-13', 34, 'Weekly', 'Isla Pucú', 'Paraguay');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (35, 'm', '2020-07-24', 35, 'Never', 'Sirājganj', 'Bangladesh');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (36, 'm', '2021-06-15', 36, 'Never', 'Huilelot', 'Indonesia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (37, 'f', '2020-09-04', 37, 'Monthly', 'Imishli', 'Azerbaijan');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (38, 'm', '2020-10-06', 38, 'Never', 'Téra', 'Niger');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (39, 'm', '2020-11-16', 39, 'Seldom', 'Imishli', 'Azerbaijan');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (40, 'f', '2021-06-20', 40, 'Often', 'Kudara-Somon', 'Russia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (41, 'f', '2020-12-22', 41, 'Monthly', 'Gaoliang', 'China');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (42, 'f', '2021-04-14', 42, 'Once', 'Urzuf', 'Ukraine');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (43, 'f', '2021-04-23', 43, 'Often', 'Zavrč', 'Slovenia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (44, 'm', '2021-05-10', 44, 'Monthly', 'Tembol', 'Indonesia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (45, 'f', '2020-11-07', 45, 'Seldom', 'Benito Juarez', 'Mexico');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (46, 'f', '2021-07-08', 46, 'Once', 'Hlusk', 'Belarus');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (47, 'f', '2020-12-03', 47, 'Yearly', 'Palma De Mallorca', 'Spain');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (48, 'm', '2020-09-28', 48, 'Daily', 'Rybnik', 'Poland');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (49, 'm', '2020-09-09', 49, 'Never', 'Wau', 'Papua New Guinea');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (50, 'f', '2021-01-06', 50, 'Weekly', 'Fosses', 'France');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (51, 'f', '2020-08-26', 51, 'Often', 'Sacotes', 'Portugal');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (52, 'm', '2021-07-02', 52, 'Seldom', 'Rabat', 'Malta');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (53, 'm', '2021-04-03', 53, 'Once', 'Godziszów Pierwszy', 'Poland');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (54, 'm', '2021-06-17', 54, 'Daily', 'Saint-Raymond', 'Canada');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (55, 'm', '2020-11-08', 55, 'Monthly', 'Housuo', 'China');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (56, 'f', '2020-12-07', 56, 'Never', 'Beltinci', 'Slovenia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (57, 'm', '2021-02-09', 57, 'Never', 'Aravissós', 'Greece');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (58, 'm', '2021-01-02', 58, 'Weekly', 'Alegria', 'Philippines');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (59, 'm', '2020-10-09', 59, 'Monthly', 'Zduńska Wola', 'Poland');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (60, 'f', '2020-10-24', 60, 'Seldom', 'Göteborg', 'Sweden');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (61, 'f', '2021-01-29', 61, 'Monthly', 'Baran', 'Indonesia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (62, 'm', '2021-06-22', 62, 'Once', 'Nassarawa', 'Nigeria');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (63, 'f', '2020-09-01', 63, 'Once', 'Estefania', 'Philippines');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (64, 'm', '2020-12-06', 64, 'Once', 'Jiazi', 'China');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (65, 'f', '2020-10-30', 65, 'Seldom', 'Aihua', 'China');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (66, 'm', '2021-04-10', 66, 'Daily', 'Pirojpur', 'Bangladesh');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (67, 'f', '2020-07-13', 67, 'Monthly', 'Taihe', 'China');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (68, 'f', '2020-10-25', 68, 'Yearly', 'Labrador', 'Philippines');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (69, 'm', '2021-04-23', 69, 'Yearly', 'Woja', 'Indonesia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (70, 'm', '2021-03-09', 70, 'Weekly', 'Balingcanaway', 'Philippines');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (71, 'f', '2021-02-18', 71, 'Monthly', 'Herzliya Pituah', 'Israel');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (72, 'm', '2020-07-25', 72, 'Monthly', 'Неготино', 'Macedonia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (73, 'f', '2020-10-15', 73, 'Once', 'Victoria', 'Philippines');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (74, 'm', '2021-01-11', 74, 'Once', 'Bektemir', 'Uzbekistan');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (75, 'f', '2020-08-12', 75, 'Often', 'Elx/Elche', 'Spain');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (76, 'm', '2020-09-30', 76, 'Never', 'Malaga', 'Spain');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (77, 'm', '2021-07-02', 77, 'Once', 'Jinshi', 'China');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (78, 'm', '2021-01-23', 78, 'Weekly', 'Göteborg', 'Sweden');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (79, 'f', '2021-05-03', 79, 'Once', 'Segodim', 'Portugal');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (80, 'm', '2020-08-22', 80, 'Never', 'San Luis', 'Colombia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (81, 'f', '2020-10-27', 81, 'Once', 'Zhaolingpu', 'China');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (82, 'm', '2021-01-31', 82, 'Once', 'San Diego', 'United States');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (83, 'm', '2020-08-02', 83, 'Weekly', 'Najiaying', 'China');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (84, 'f', '2021-03-11', 84, 'Once', 'Zainsk', 'Russia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (85, 'f', '2021-03-06', 85, 'Weekly', 'Curahkalak Tengah', 'Indonesia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (86, 'm', '2020-10-20', 86, 'Never', 'Sevan', 'Armenia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (87, 'f', '2021-04-17', 87, 'Monthly', 'Nagutskoye', 'Russia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (88, 'f', '2020-09-06', 88, 'Never', 'Bumbuna', 'Sierra Leone');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (89, 'f', '2020-10-25', 89, 'Yearly', 'Salcedo', 'Philippines');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (90, 'f', '2020-10-12', 90, 'Once', 'Yangdian', 'China');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (91, 'f', '2021-02-16', 91, 'Daily', 'Tomioka', 'Japan');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (92, 'f', '2021-01-20', 92, 'Seldom', 'Lefortovo', 'Russia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (93, 'f', '2020-09-27', 93, 'Never', 'Bajingmeduro', 'Indonesia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (94, 'm', '2020-11-15', 94, 'Often', 'Mingshan', 'China');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (95, 'm', '2021-06-25', 95, 'Yearly', 'Podgortsy', 'Ukraine');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (96, 'f', '2021-04-16', 96, 'Once', 'Ledoy', 'Peru');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (97, 'f', '2021-05-30', 97, 'Daily', 'Leeds', 'United Kingdom');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (98, 'm', '2021-05-11', 98, 'Often', 'Dragomer', 'Slovenia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (99, 'm', '2021-07-11', 99, 'Never', 'Ketapang', 'Indonesia');
insert into profiles_insert (user_id, gender, birthday, photo-id, user_status, city, country) values (100, 'f', '2020-12-03', 100, 'Often', 'Waterloo', 'Canada');
